theme: jekyll-theme-leap-day




title: [Shyngys's homepage]
description: [Welcome to my homepage!]

show_downloads: ["true"]

github:
  zip_url: https://github.com/ShyngysM/my_achievements.git/download.zip
