theme: jekyll-theme-leap-day




title: [The title of your site]
description: [A short description of your site's purpose]

show_downloads: ["true"]

github:
  zip_url: https://github.com/ShyngysM/my_achievements/blob/main/Empfehlungsschreiben_Shyngys_Muratbek_Praktikum_page-0001.jpg
