theme: jekyll-theme-leap-day




title: [Welcome to my homepage!]
description: [Bookmark this to keep an eye on my project updates!]

show_downloads: ["true"]

github:
  zip_url: https://github.com/ShyngysM/my_achievements/blob/main/Empfehlungsschreiben_Shyngys_Muratbek_Praktikum_page-0001.jpg
